# Generated by Django 3.2.10 on 2022-01-07 09:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField()),
                ('price_per_unit_retail', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_per_unit_wholesale', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('tax_amount', models.IntegerField(null=True)),
                ('is_retail', models.BooleanField(default=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_products', to='products.products')),
            ],
        ),
        migrations.CreateModel(
            name='SalesStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_paid', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('sale_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('sale_amount_paid', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('tax_amount', models.IntegerField(null=True)),
                ('products', models.ManyToManyField(related_name='product_in_sales', through='sales.ProductSales', to='products.Products')),
                ('sales_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='sales.salesstatus')),
            ],
            options={
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.AddField(
            model_name='productsales',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_sales', to='sales.sales'),
        ),
    ]
