# Generated by Django 3.2.10 on 2022-01-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsales',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='productsales',
            name='price_per_unit_retail',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='productsales',
            name='price_per_unit_wholesale',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='productsales',
            name='tax_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
