# Generated by Django 3.2.10 on 2022-01-08 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20220108_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsales',
            name='sales',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_to_sales', to='sales.sales'),
        ),
    ]
