# Generated by Django 3.2.10 on 2022-01-08 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_productsales_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sales_status',
            field=models.ForeignKey(blank=True, default='sold', on_delete=django.db.models.deletion.CASCADE, related_name='status', to='sales.salesstatus'),
        ),
    ]
