# Generated by Django 3.2.10 on 2022-01-10 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_sales_sales_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsales',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_status',
            field=models.ForeignKey(blank=True, default='Sold', on_delete=django.db.models.deletion.CASCADE, related_name='status', to='sales.salesstatus'),
        ),
    ]
