# Generated by Django 3.2.10 on 2022-01-04 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('name',), 'verbose_name_plural': 'Products'},
        ),
    ]
