# Generated by Django 3.2.10 on 2022-01-06 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('products', '0008_auto_20220105_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField()),
                ('price_per_unit_retail', models.IntegerField()),
                ('price_per_unit_wholesale', models.IntegerField()),
                ('price', models.IntegerField()),
                ('tax_amount', models.IntegerField(null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sales')),
            ],
        ),
    ]
